# Generated by Django 5.0.6 on 2024-05-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_possibility_alter_poll_table_alter_question_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='possibilites',
            new_name='possibilities',
        ),
    ]
