# Generated by Django 5.0.6 on 2024-06-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_participant_email_alter_participant_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_possibiity',
            new_name='question_possibility',
        ),
    ]
