# Generated by Django 5.0.6 on 2024-05-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_possibilites_question_possibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='possibilities',
            field=models.ManyToManyField(blank=True, to='polls.possibility'),
        ),
    ]
