# Generated by Django 5.0.6 on 2024-06-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_question_possibiity_answer_question_possibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpossibility',
            name='possibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.possibility'),
        ),
    ]
