# Generated by Django 5.0.6 on 2024-06-11 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possibility',
            options={'verbose_name_plural': 'Possibliities'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
