# Generated by Django 5.0.6 on 2024-06-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_possibility_options_alter_poll_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
