# Generated by Django 5.0.6 on 2024-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_participant_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
