# Generated by Django 5.0.6 on 2024-06-13 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
